### PR TITLE
remove excess dependency illuminate/support from container

### PR DESCRIPTION
**Pull request by mixartemev**
thought from [this discussion](https://github.com/mixartemev/framework/pull/3#discussion_r306925644)
and some clean up code

### CODE REVIEW

**Comment by driesvints** [comment]
Heya,

Thanks for your PR. You've submitted this on the Illuminate organization which is a read-only sub split of `laravel/framework`. Please submit your PR on the https://github.com/laravel/framework repository. 

Thanks!

**Review by Traverse06 — COMMENTED** [review]
Erase

**Review by Traverse06 — COMMENTED** [review]
-

**Review by Traverse06 — COMMENTED** [review]
Erase

**Pull request closed without merging**
